### ISSUE TITLE
Custom loaders

### ISSUE THREAD

**Issue by dotba** [timreichen/Bundler#27]
How we can create a custom loaders to cover more files (like in webpack)?

**Comment by timreichen** [comment]
I am working on an overdo atm because I am not happy with the current plugin/loader implementation and also to fix some bugs and maybe gain some performance. I hope to get the 0.5 version released next week. The new implementation will have plugin classes instead of functions to be more expressive.
What file type are you interested specifically?
As for using plugins/loaders: There will always be the option to create a custom bundler instance. However, I would also be keen on introducing some kind of custom plugin loading via cli `--plugin my_plugin.ts` or something similar. This is up for debate and ideas are welcome.

**Comment by lowray** [comment]
Actually I was looking for a loader for SCSS/SASS files.

**Comment by timreichen** [comment]
I am eager to add a css preprocessor loader but to my knowledge there is working sass module that can be used to transpile sass/scss to css in deno yet. I tried esm.sh and jspm.dev without success.

**Comment by timreichen** [comment]
I had some discussions with different front end devs. Since the functionality of css has grown over the last years and postcss is built into the bundler, I think bundler will support only native css for the moment.
Nesting, variables, prefixing etc. are now either part of css and supported by browsers or polyfilled by [postcss-preset-env](https://preset-env.cssdb.org).

For what functionality would you like to use scss/sass rather than native css?

**Comment by timreichen** [comment]
Closing for non-activity. Feel free to reopen again.
